---
# Source: akri/templates/debug-echo-configuration.yaml
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-debug-echo
spec:
  discoveryHandler: 
    name: debugEcho
    discoveryDetails: |+
      descriptions:
      - foo0
      - foo1
  brokerPodSpec:
    containers:
    - name: akri-debug-echo-broker
      image: perl
      command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      resources:
        requests:
          "{{PLACEHOLDER}}" : "1"
        limits:
          "{{PLACEHOLDER}}" : "1"
    restartPolicy: Never
  instanceServiceSpec:
    type: ClusterIP
    ports:
    - name: akri-debug-echo-foo-instance-service
      port: 6052
      protocol: TCP
      targetPort: 6052
  configurationServiceSpec:
    type: ClusterIP
    ports:
    - name: akri-debug-echo-foo-configuration-service
      port: 6052
      protocol: TCP
      targetPort: 6052
  brokerProperties:
    IS_JOB: "1"
    JOB_DESIRED_STATE: "1"
  capacity: 2
